name: bat
channels:
  - conda-forge
  - bioconda
channel_priority: strict

dependencies:
  # Python runtime
  - python >=3.9,<3.13
  - biopython

  # Sequence alignment / phylogeny tools
  - blast
  - clustalo
  - prank
  - trimal
  - fasttree
  - mafft >=7,<8
  - hmmer
  - raxml-ng=1.2.2 
